"""
Report Generator Module for Issue Triage Application.

Generates a comprehensive markdown report from triaged issues,
statistics, and charts. The report includes summary statistics,
category breakdowns, and individual issue listings.

Requirements:
- English only
- Type hints in all functions
- Uses logging instead of print statements
"""

import logging
from pathlib import Path
from typing import List, Dict, Any

from .models import Issue, IssueStats
from .stats import get_report_snapshot

logger = logging.getLogger("issue_triage.reporter")
if not logger.handlers:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )


def generate_report(
    issues: List[Issue],
    stats: IssueStats,
    output_path: str,
) -> Path:
    """Generate a markdown report for triaged issues.

    Args:
        issues: List of categorized Issue instances.
        stats: The IssueStats instance with aggregated statistics.
        output_path: Path where the markdown report will be saved.

    Returns:
        Path to the generated markdown report file.
    """
    logger.info("Generating markdown report for %d issues.", len(issues))

    output_dir = Path(output_path).parent
    output_dir.mkdir(parents=True, exist_ok=True)
    report_path = output_dir / Path(output_path).name

    snapshot = get_report_snapshot(stats)

    lines: List[str] = []
    lines.append("# Issue Triage Report")
    lines.append("")
    lines.append(f"**Project:** github_issue_triage")
    lines.append(f"**Total Issues:** {stats.total}")
    lines.append(f"**Categories:** {snapshot['total_categories']}")
    lines.append("")

    # --- Summary Statistics ---
    lines.append("## Summary Statistics")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("| --- | --- |")
    lines.append(f"| Total Issues | {stats.total} |")
    lines.append(f"| Valid Categories | {snapshot['total_categories']} |")
    lines.append(f"| Issues by Category | {', '.join(snapshot['category_counts'].keys())} |")
    lines.append("")

    # --- Category Breakdown ---
    lines.append("## Category Breakdown")
    lines.append("")
    lines.append("| Category | Count | Percentage |")
    lines.append("| --- | --- | --- |")
    for category, count in snapshot["category_counts"].items():
        percentage = (count / stats.total * 100) if stats.total > 0 else 0
        lines.append(f"| {category} | {count} | {percentage:.1f}% |")
    lines.append("")

    # --- Individual Issues ---
    lines.append("## Individual Issues")
    lines.append("")
    lines.append("| ID | Title | Category | Description |")
    lines.append("| --- | --- | --- | --- |")

    for issue in issues:
        title = issue.title.replace("|", "\\|")
        desc = issue.description.replace("|", "\\|").replace("\n", " ")
        lines.append(f"| {issue.id} | {title} | {issue.category.value} | {desc} |")

    lines.append("")

    # --- Charts Reference ---
    lines.append("## Visualizations")
    lines.append("")
    lines.append("The following charts were generated for this triage:")
    lines.append("")
    lines.append("- **Category Distribution:** `category_distribution.png`")
    lines.append("- **Category Counts:** `category_counts.png`")
    lines.append("")

    # --- Conclusion ---
    lines.append("## Conclusion")
    lines.append("")
    if stats.total == 0:
        lines.append("No issues were processed for this report.")
    else:
        lines.append(
            f"A total of {stats.total} issues have been triaged. "
            f"Statistics have been generated and charts "
            f"have been created for visualization."
        )
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        "*Report generated by github_issue_triage application. "
        "Clean architecture with type hints and logging.*"
    )

    report_content = "\n".join(lines)
    with open(report_path, "w", encoding="utf-8") as file:
        file.write(report_content)

    logger.info("Saved report: %s", report_path)
    return report_path
